Repository EntryDSM/Volvo, pull requests merged in 2021-12, with the labels that each got.

#54 (#52) 지원자 인적사항 api 연동 오류
  volvo/src/components/default/pagination/PageBtn.tsx
  volvo/src/components/default/pagination/index.tsx
  volvo/src/components/grade/index.tsx
  volvo/src/components/information/index.tsx
  volvo/src/components/information/style.ts
  volvo/src/components/preview/index.tsx
  volvo/src/components/selectType/index.tsx
  volvo/src/containers/information/index.tsx
  volvo/src/modules/redux/middleware/information/index.ts
  volvo/src/modules/redux/reducer/information/index.ts
  volvo/src/modules/redux/reducer/information/interface/index.ts
  volvo/src/types.ts
  volvo/src/util/api/information/index.ts
Labels: bug

#57 (#55) 검정고시 점수 입력 오류
  volvo/src/constance/uri.ts
Labels: bug

#58 (#58) 중학교 검색할 때 검색 결과가 없으면 없다고 띄워주기
  volvo/src/components/modal/searchSchool/SearchSchool.tsx
  volvo/src/components/modal/searchSchool/style.ts
Labels: enhancement

#41 #4 enter grade api
  volvo/src/components/grade/SettingGrade.tsx
  volvo/src/components/grade/column/VolunteerColumn.tsx
  volvo/src/components/grade/table/GradeTable.tsx
  volvo/src/components/information/column/PictureBtn.tsx
  volvo/src/constance/grade/index.ts
  volvo/src/containers/grade/index.tsx
  volvo/src/modules/redux/action/grade/index.ts
  volvo/src/modules/redux/middleware/grade/index.ts
  volvo/src/modules/redux/middleware/index.ts
  volvo/src/modules/redux/reducer/grade/index.ts
  volvo/src/modules/redux/reducer/grade/interface/index.ts
  volvo/src/types.ts
  volvo/src/util/api/grade/index.ts
  volvo/src/util/hooks/grade/index.ts
Labels: enhancement

#62 (#61) 지원자 성적 입력 페이지네이션
  volvo/src/components/default/pagination/PageBtn.tsx
  volvo/src/components/grade/index.tsx
Labels: enhancement

#64 (#63) Refresh Token
  volvo/src/containers/header/index.tsx
  volvo/src/modules/redux/action/signin/index.ts
  volvo/src/modules/redux/middleware/signin/index.ts
  volvo/src/modules/redux/reducer/signin/index.ts
  volvo/src/util/api/signin/index.ts
Labels: bug

#65 (#59) 지원자 미리보기 pdf
  volvo/src/components/default/pagination/PageBtn.tsx
  volvo/src/components/information/column/PictureBtn.tsx
  volvo/src/components/information/index.tsx
  volvo/src/components/preview/Pdf.tsx
  volvo/src/components/preview/index.tsx
  volvo/src/components/preview/style.ts
  volvo/src/modules/redux/action/preview/index.ts
  volvo/src/modules/redux/reducer/preview/index.ts
  volvo/src/modules/redux/reducer/preview/interface/index.ts
  volvo/src/modules/redux/reducer/signin/index.ts
  volvo/src/util/api/preview/index.ts
Labels: enhancement

#67 66 auto save
  volvo/src/modules/redux/action/introduction/index.ts
  volvo/src/modules/redux/action/introduction/interface/index.ts
  volvo/src/modules/redux/middleware/index.ts
  volvo/src/modules/redux/middleware/introduction/index.ts
  volvo/src/modules/redux/reducer/index.ts
  volvo/src/modules/redux/reducer/introduction/index.ts
  volvo/src/modules/redux/reducer/introduction/interface/index.ts
  volvo/src/util/api/introduction/index.ts
Labels: enhancement

#69 ⚡️ :: (#68) 자기소개서 작업계획서 불러오는 기능 추가
  volvo/src/components/coverLetterAndStudyPlan/descriptionAndInput/index.tsx
  volvo/src/components/coverLetterAndStudyPlan/index.tsx
  volvo/src/components/coverLetterAndStudyPlan/styles.ts
  volvo/src/components/introduction/descriptionAndInput/index.tsx
  volvo/src/components/introduction/index.tsx
  volvo/src/components/introduction/styles.ts
  volvo/src/containers/introduction/index.tsx
  volvo/src/router/MainRouter.tsx
Labels: enhancement

#73 ⚡️ :: (#71) 자기소개서 작성 페이지 진입시 null값으로인해 발생하는 오류 수정
  volvo/src/modules/redux/middleware/introduction/index.ts
Labels: bug

#74 ⚡️::(#72) 스크롤 바 색깔 수정 및 이상한 코드 삭제
  volvo/src/components/introduction/descriptionAndInput/index.tsx
  volvo/src/components/introduction/styles.ts
Labels: enhancement

#75 (#70) 자기소개서 & 학업계획서 페이지네이션
  volvo/src/components/default/pagination/PageBtn.tsx
  volvo/src/components/introduction/index.tsx
  volvo/src/containers/introduction/index.tsx
  volvo/src/modules/redux/middleware/introduction/index.ts
  volvo/src/modules/redux/reducer/introduction/index.ts
  volvo/src/modules/redux/reducer/introduction/interface/index.ts
  volvo/src/style/GlobalStyle.ts
Labels: enhancement

#77 (#76) 유저 상태 박스
  volvo/src/components/header/style.ts
  volvo/src/types.ts
  volvo/src/util/api/user/index.ts
Labels: bug

#79 (#78) 헤더 정보가 저장이 안됨
  volvo/src/util/api/user/index.ts
Labels: bug

#83 (#80) 생일 저장 수정 & totalSocre api 요청 수정
  volvo/src/modules/redux/reducer/information/index.ts
Labels: bug

#82 Create main.yml
  .github/workflows/main.yml
Labels: enhancement

#85 (#84) 로그인 전 & 최종제출 후 원서 작성 막기
  volvo/src/containers/grade/index.tsx
  volvo/src/containers/information/index.tsx
  volvo/src/containers/introduction/index.tsx
  volvo/src/containers/preview/index.tsx
  volvo/src/containers/selectType/index.tsx
  volvo/src/util/api/default/index.ts
  volvo/src/util/hooks/preview/usePreview.tsx
Labels: enhancement

#87 (#86) 전형구분 리덕스 리팩토링
  volvo/src/modules/redux/action/selectType/index.ts
  volvo/src/modules/redux/middleware/selectType/index.ts
  volvo/src/modules/redux/reducer/selectType/index.ts
Labels: refactor

#92 (#91) 최종제출시 제출 서류 다운로드 버튼으로 수정
  volvo/src/components/main/content/MainButton.tsx
  volvo/src/components/main/content/index.tsx
  volvo/src/components/main/index.tsx
  volvo/src/containers/main/index.tsx
Labels: enhancement

#93 (#88) 인적사항 리덕스 리팩토링 하기
  volvo/src/components/main/progress/progressContent.tsx
  volvo/src/modules/redux/action/information/index.ts
  volvo/src/modules/redux/middleware/information/index.ts
  volvo/src/modules/redux/reducer/information/index.ts
Labels: refactor

#95 ⚡️:: (#94) grade style 수정
  volvo/src/components/grade/style.ts
Labels: refactor

#96 (#89) 미리보기 리덕스 리팩토링 하기
  volvo/src/components/main/content/index.tsx
  volvo/src/modules/redux/reducer/preview/index.ts
Labels: refactor
